# Hi!

# This file customizes a web page template with your info.
# Type in the appropriate info items below

# Lines of text that begin with # are COMMENTS.

# Comments are ignored by the software that feeds your info below
# into the web page template.

# This file is a part of the HSHSL workshop Using GitHub to Manage Your Scholarly Work.

name: Mary Anne Melo
email: mmelo@umaryland.edu
job_title: assistant professor
degrees: ["DDS,""MS","Ph.D"] # type your degrees inside the square brackets in quotes and separated by a comma, ie: ["BA","MS","Ph.D"]
institution_name: University of Maryland
institution_URL: https://www.dental.umaryland.edu/
department_name: Endodontics,Prosthodontics and Operative Dentistry
department_URL: https://www.dental.umaryland.edu/epod/operative-dentistry/faculty/
github_username: maryannesmelo
twitter_username: 
linkedin_URL: 
selfie_URL: https://placehold.it/350x350

social:
  have_twitter: false
  have_linkedin: false

# Technical configuration
markdown: kramdown
permalinks: pretty
